Draft - Add models context
damianpereira86/api-automation-agent pull request #48
Opened 2024-12-30 02:17 UTC by damianpereira86

This PR is an alternative to https://github.com/damianpereira86/api-automation-agent/pull/43

2025-02-04 20:01 UTC, Shadowsx3 requested changes

2025-02-04 20:01 UTC, Shadowsx3 commented on src/services/llm_service.py
> +        # TODO: This should use a smaller model (e.g. Haiku)
Can we do this now?

2025-02-05 13:48 UTC, damianpereira86 commented on src/ai_tools/file_reading_tool.py
> +                fileSpec = {
Done

2025-02-05 13:54 UTC, damianpereira86 commented on src/ai_tools/file_reading_tool.py
> +        return all_read_files
Done

2025-02-05 13:55 UTC, damianpereira86 commented on src/ai_tools/file_reading_tool.py
> +    async def _arun(self, files: List[str]) -> str:
Done

2025-02-05 14:03 UTC, damianpereira86 commented on src/framework_generator.py
>              models = None
Done

2025-02-05 14:08 UTC, damianpereira86 commented on src/services/llm_service.py
> +            if tool_to_use is not None:
Done

2025-02-05 14:24 UTC, damianpereira86 commented on src/framework_generator.py
> +                if not self._should_process_endpoint(path["path"]):
Created a task to review this

2025-02-05 14:38 UTC, damianpereira86 commented on src/services/llm_service.py
> +        # TODO: This should use a smaller model (e.g. Haiku)
Done

2025-02-07 18:55 UTC, Shadowsx3 approved these changes

2025-02-07 18:57 UTC, merged